require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# React Native Permissions 설정
require_relative '../node_modules/react-native-permissions/scripts/setup'
setup_permissions([
  'Bluetooth'
])

target 'WebAppWrapper' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => true
  )

  # 필요한 다른 pod들을 여기에 추가하세요
  pod 'react-native-ble-manager', :path => '../node_modules/react-native-ble-manager'
  pod 'react-native-ble-plx', :path => '../node_modules/react-native-ble-plx'

  target 'WebAppWrapperTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
      end
    end
  end
end